### ISSUE TITLE
How to load the data - typo

### ISSUE THREAD

**Issue by gemini-mouse** [TwQin0403/twstock_downloader#1]
我發現為什麼這支程式這麼少人使用了...

文檔這邊寫錯了

with open('result.json','r',encoding='utf-8') as f:
    test_data = json.load(f)

test_data.pop('current'.None)    <---------   應該改成逗號才對    test_data.pop('current', None)  
test_data = {key:pd.read_json(test_data[key]) for key in test_data.keys()} 

不然執行起來會有錯誤，很多人就會放棄使用喔

**Comment by TwQin0403** [comment]
十分感謝指出這個問題，已修正
